### ISSUE TITLE
Repo not found

### ISSUE THREAD

**Issue by davewd** [vivaxy/vscode-conventional-commits#15]
Keep getting this error : 
Conventional Commits: repo not found in path: /Users/<username>/Documents/projects

**Comment by vivaxy** [comment]
Thanks you for your feedback. Please follow the [gather logs](https://github.com/vivaxy/vscode-conventional-commits#gather-logs) section and paste the logs here.

**Comment by vivaxy** [comment]
Closed for no response.

**Comment by davewd** [comment]
Hey @vivaxy i think the problem is that the extension only works when the working directory == github reporitory.  in the workspace i was trying to use i have the following setup :

woring directory
|
-repo a
-repo b
-repo c

**Comment by davewd** [comment]
in order to function correctly i think the extension needs to disassociate the working directory from the github repo directory and understand that theres can be a 1:n mapping

**Comment by vivaxy** [comment]
@davewd I think you can try to use `Add folder to workspace` instead of opening the parent folder of some git repos.

![image](https://user-images.githubusercontent.com/4216856/82743385-44ec8900-9d9d-11ea-9034-aef1c03abb22.png)

The opened workspace looks like this:
![image](https://user-images.githubusercontent.com/4216856/82743390-5766c280-9d9d-11ea-9531-3794558683af.png)

After committing, VSCode will prompt for the git repo.
![image](https://user-images.githubusercontent.com/4216856/82743372-11116380-9d9d-11ea-919d-cedf08bfef34.png)
